### ISSUE TITLE
CollectionFS compatibility issue

### ISSUE THREAD

**Issue by scsirdx** [ongoworks/meteor-security#20]
Hi!
I'm using ongoworks:security@1.1.0 and cfs:collection@0.5.5.
When i try to set security rules like this:
```javascript
StickerImages.files.permit(['download']).ifLoggedIn().apply();
```
I got an error:
```
W20150512-17:38:11.681(3)? (STDERR) Error: allow: Invalid key: download
W20150512-17:38:11.682(3)? (STDERR)     at packages/mongo/collection.js:723:1
W20150512-17:38:11.682(3)? (STDERR)     at Array.forEach (native)
W20150512-17:38:11.682(3)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20150512-17:38:11.682(3)? (STDERR)     at [object Object].addValidator (packages/mongo/collection.js:721:1)
W20150512-17:38:11.682(3)? (STDERR)     at [object Object].Mongo.Collection.allow (packages/mongo/collection.js:769:1)
W20150512-17:38:11.683(3)? (STDERR)     at packages/ongoworks:security/security-util.js:39:1
W20150512-17:38:11.683(3)? (STDERR)     at Array.forEach (native)
W20150512-17:38:11.683(3)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20150512-17:38:11.683(3)? (STDERR)     at addFuncForAll (packages/ongoworks:security/security-util.js:38:1)
W20150512-17:38:11.683(3)? (STDERR)     at packages/ongoworks:security/security-util.js:56:1
```

But the following rule works great:
```javascript
StickerImages.deny({
    download: function(userId, doc){
        return true;
    }
});
```

Is it a compatibility problem, or i'm doing something wrong?

**Comment by chompomonim** [comment]
Getting same problem. Any ideas how to fix this?

**Comment by vantonio** [comment]
Hit the same problem today. Has it something to do with autoform?

**Comment by aldeed** [comment]
Can one of you try cloning this package into your /packages folder and add this in Package.onUse in package.js:

```js
api.use("cfs:collection", ["client", "server"], {weak: true});
```

If that fixes it, we can do an update.

**Comment by vantonio** [comment]
Hi @aldeed,

This follwoing steps results in the same error:
```
mkdir packages && cd packages
git clone https://github.com/ongoworks/meteor-security.git 
```
changed package name from ```ongoworks:security``` to ```security```
added ```api.use("cfs:collection", ["client", "server"], {weak: true});``` to ```package.onUse``` section.

```
export PACKAGE_DIRS=$HOME/projects/myAPP/packages
meteor add security
```
then add this two lines
```
Photos.files.permit(['insert', 'update', 'remove']).ifLoggedIn().apply();
Photos.files.permit(['download']).ifLoggedIn().apply();
```

Throws same error:
```
Error: allow: Invalid key: download
    at packages/mongo/collection.js:723:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at [object Object].addValidator (packages/mongo/collection.js:721:1)
    at [object Object].Mongo.Collection.allow (packages/mongo/collection.js:769:1)
    at packages/security/security-util.js:39:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at addFuncForAll (packages/security/security-util.js:38:1)
    at packages/security/security-util.js:56:1
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by vantonio** [comment]
Oh I've also removed the ```ongoworks:security``` before the steps. Thanks.

**Comment by vantonio** [comment]
I can confirm that this trick from https://github.com/ongoworks/meteor-security/issues/17 works.
```
Security.permit(['download']).collections([Photos]).apply();
```

**Comment by tcastelli** [comment]
+1

**Comment by tinchoz49** [comment]
:+1:

**Comment by aldeed** [comment]
Should be fixed by https://github.com/ongoworks/meteor-security/commit/4a4c0ba523b035915a715ec377f2e985c874622b in 1.3.0
